
def gcd(a, b):
    if a % b == 0:
        return b
    return gcd(b, a % b)

"""
Z_n^* contains all the invertible elements in (Z_n, *).
That is, it contains all x in Z_n where gcd(x, n) == 1.

The function below returns the elements of Z_n^* for
some input n.
"""
def get_elems(n):
    z_n_star = {1}
    for i in range(2, n):
        if gcd(i, n) == 1:
            z_n_star.add(i) 
    return z_n_star  

# Returns the set generated by a under *.
def generate(a, n):
    generated = {a}
    cur = a
    while cur != 1:
        cur = (cur * a) % n
        generated.add(cur)
    return generated

# Returns the set of generators for Z_n^*.
def get_generators(n):
    z_n_star = get_elems(n)
    generators = set([])
    for a in z_n_star:
        if z_n_star == generate(a, n):
            generators.add(a)
    return generators         

print(get_generators(25))
